name: dawn
options:
  bundleIdPrefix: app.opendawn
  deploymentTarget:
    macOS: &deployversion "26.0"

settings:
  base:
    SWIFT_VERSION: &swiftversion "6"
    MARKETING_VERSION: &mktversion "0.1.0"
    CURRENT_PROJECT_VERSION: &buildversion "1"

packages:
  dawnLogging:
    path: LocalPackages/dawnLogging

targets:

  dawnApp:
    type: application
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnApp
    info:
      path: dawnApp/Info.plist
      properties:
        CFBundleName: DAWN
        CFBundleDisplayName: DAWN
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSApplicationCategoryType: public.app-category.utilities
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSHumanReadableCopyright: "Copyright © 2026 Open Dawn"
    settings:
      base:
        PRODUCT_NAME: DAWN
        PRODUCT_MODULE_NAME: dawnApp
        MARKETING_VERSION: *mktversion
        CURRENT_PROJECT_VERSION: *buildversion
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - target: libdawn
      - target: dawnAgent
        link: false
        embed: true
        copy:
          destination: wrapper
          subpath: Contents/Library/LoginItems
      - package: dawnLogging
    scheme:
      testTargets:
        - dawnAppTests
      gatherCoverageData: true

  dawnAgent:
    type: application
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAgent
    info:
      path: dawnAgent/Info.plist
      properties:
        CFBundleName: "DAWN Agent"
        CFBundleDisplayName: "DAWN Agent"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2026 Open Dawn"
    settings:
      base:
        PRODUCT_NAME: dawnAgent
        MARKETING_VERSION: *mktversion
        CURRENT_PROJECT_VERSION: *buildversion
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - target: libdawn
      - package: dawnLogging
    scheme:
      testTargets:
        - dawnAgentTests
      gatherCoverageData: true

  libdawn:
    type: framework
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: libdawn
        excludes:
          - README.md
          - Docs/**
    info:
      path: libdawn/Info.plist
      properties:
        CFBundleName: libdawn
        CFBundleDisplayName: libdawn
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSHumanReadableCopyright: "Copyright © 2026 Open Dawn"
    settings:
      base:
        PRODUCT_NAME: libdawn
        MARKETING_VERSION: *mktversion
        CURRENT_PROJECT_VERSION: *buildversion
        SWIFT_VERSION: *swiftversion
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - package: dawnLogging
    scheme:
      testTargets:
        - libdawnTests
      gatherCoverageData: true

  libdawnTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - libdawnTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
    dependencies:
      - target: libdawn

  dawnAgentTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAgentTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/dawnAgent.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/dawnAgent
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: dawnAgent
      - target: libdawn

  dawnAppTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAppTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/DAWN.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/DAWN
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: dawnApp
      - target: libdawn

schemes:
  dawn:
    build:
      targets:
        libdawn: all
        dawnAgent: all
        dawnApp: all
        libdawnTests: [test]
        dawnAgentTests: [test]
        dawnAppTests: [test]
    test:
      gatherCoverageData: true
      targets:
        - libdawnTests
        - dawnAgentTests
        - dawnAppTests
        - package: dawnLogging/dawnLoggingTests
