name: dawn
options:
  bundleIdPrefix: app.opendawn

settings:
  base:
    SWIFT_VERSION: &swiftversion "6"

packages:
  dawnLogging:
    path: LocalPackages/dawnLogging

targets:

  dawnApp:
    type: application
    platform: macOS
    deploymentTarget: &deployversion "26.0"
    sources:
      - dawnApp
    info:
      path: dawnApp/Info.plist
      properties:
        CFBundleDisplayName: "DAWN Settings"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
    settings:
      base:
        MARKETING_VERSION: &mktversion "0.0.0"
        CURRENT_PROJECT_VERSION: &buildversion "1"
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - target: libdawn
      - target: dawnAgent
        link: false
        embed: true
        copy:
          destination: wrapper
          subpath: Contents/Library/LoginItems
      - package: dawnLogging
    scheme:
      testTargets:
        - dawnAppTests
      gatherCoverageData: true

  dawnAgent:
    type: application
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAgent
    info:
      path: dawnAgent/Info.plist
      properties:
        CFBundleDisplayName: "DAWN Launch Agent"
        LSUIElement: true
    settings:
      base:
        MARKETING_VERSION: *mktversion
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - target: libdawn
      - package: dawnLogging
    scheme:
      testTargets:
        - dawnAgentTests
      gatherCoverageData: true
  
  libdawn:
    type: framework
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - path: libdawn
        excludes:
          - README.md
          - Docs/**
    info:
      path: libdawn/Info.plist
      properties:
        CFBundleDisplayName: "DAWN libdawn Framework"
    settings:
      base:
        MARKETING_VERSION: *mktversion
        SWIFT_VERSION: *swiftversion
      configs:
        Debug:
          ENABLE_TESTABILITY: YES
    dependencies:
      - package: dawnLogging
    scheme:
      testTargets:
        - libdawnTests
      gatherCoverageData: true

  libdawnTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - libdawnTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
    dependencies:
      - target: libdawn

  dawnAgentTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAgentTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/dawnAgent.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/dawnAgent
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: dawnAgent
      - target: libdawn

  dawnAppTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: *deployversion
    sources:
      - dawnAppTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      SWIFT_VERSION: *swiftversion
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/dawnApp.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/dawnApp
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: dawnApp
      - target: libdawn

schemes:
  dawn:
    build:
      targets:
        libdawn: all
        dawnAgent: all
        dawnApp: all
        libdawnTests: [test]
        dawnAgentTests: [test]
        dawnAppTests: [test]
    test:
      gatherCoverageData: true
      targets:
        - libdawnTests
        - dawnAgentTests
        - dawnAppTests
        - package: dawnLogging/dawnLoggingTests
