name: pineapplewm
options:
  bundleIdPrefix: dev.longhi.pineappleinc
targets:
  
  PaSettingsUI:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - PaSettingsUI
    info:
      path: PaSettingsUI/Info.plist
      properties:
        CFBundleDisplayName: "PineappleWM Settings"
    settings:
      MARKETING_VERSION: "0.0.0"
      SWIFT_VERSION: "6"
    dependencies:
      - target: PaEventKit
      - target: PaWM
        link: false
        embed: true
        copy:
          destination: wrapper
          subpath: Contents/Library/LoginItems
  
  PaWM:
    type: application
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - PaWM
    info:
      path: PaWM/Info.plist
      properties:
        CFBundleDisplayName: "PineappleWM Launch Agent"
        LSUIElement: true
    settings:
      MARKETING_VERSION: "0.0.0"
      SWIFT_VERSION: "6"
    dependencies:
      - target: PaEventKit
  
  PaEventKit:
    type: framework
    platform: macOS
    deploymentTarget: "26.0"
    sources:
      - PaEventKit
    info:
      path: PaEventKit/Info.plist
      properties:
        CFBundleDisplayName: "PineappleWM PaEventKit Framework"
    settings:
      MARKETING_VERSION: "0.0.0"
      SWIFT_VERSION: "6"



